# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170719_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
    ]
