export default {
    GET_ALL_NEWS_ITEMS: 'GET_ALL_NEWS_ITEMS',
    GET_ALL_BIO_PARAGRAPHS: 'GET_ALL_BIO_PARAGRAPHS',
    GET_ALL_PRESS_SHOWS: 'GET_ALL_PRESS_SHOWS',
    GET_ALL_MEDIA_ITEMS: 'GET_ALL_MEDIA_ITEMS',
}
