# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(blank=True, upload_to=b'resumes'),
        ),
    ]
