# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_auto_20170506_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'uploaded_images'),
        ),
    ]
