# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_auto_20170904_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
    ]
